export const FETCH_STOCKS = "FETCH_STOCKS";
export const FETCH_TOP_STOCKS = "FETCH_TOP_STOCKS";
export const GROWING_TODAY = "GROWING_TODAY";
export const YESTERDAY_GAINERS_LIST = "YESTERDAY_GAINERS_LIST";
export const YESTERDAY_LOSERS_LIST = "YESTERDAY_LOSERS_LIST";